show_downloads: false

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

title: Emma Cann
description: Data Science & ML Systems Professional  
Bridging behavioral science, statistical modeling, and production machine learning systems.


url: "https://cann-emma.github.io"
baseurl: "/portfolio"

collections:
  projects:
    output: true
