title: Emmanuella Cann's Portfolio
description: Hello and welcome! I'm Emmanuella (Emma) Cann, a Behavioral Neuroscience and Data Science student with a passion for data analytics, exploratory data analysis, and machine learning. This repository showcases my academic work, projects, and accomplishments in leveraging data to uncover insights and solve complex problems. I am continuously expanding my skills and knowledge, and Iâ€™m excited to apply my analytical expertise to real-world challenges.
show_downloads: False
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 






